[package]
name = "amms"
version = "1.9.10"
edition = "2021"
license = "MIT"
description = "A library to interact with automated market makers across EVM chains."
readme = "README.md"
homepage = "https://github.com/D-lyw/amms-rs"
repository = "https://github.com/D-lyw/amms-rs"
keywords = ["ethereum", "amm", "mev"]
exclude = ["target/*", ".github/*", ".gitignore", "build.rs", "contracts/*"]


[dependencies]
# darkforest
uniswap_v3_math = "0.6.2"

# alloy
alloy = { version = "1.0.25", features = ["contract", "network", "rpc", "rpc-types", "provider-ws", "rpc-types-eth", "signer-local", "reqwest-rustls-tls"] }

# tracing
eyre = "0.6"
tracing = "0.1"

# async
tokio = { version = "1.42", default-features = false, features = ["time"] }
futures = "0.3"
async-trait = "0.1"

# misc
thiserror = "1.0"
rug = "1.24.1"
itertools = "0.14.0"
rayon = "1.11.0"
async-stream = "0.3.6"
serde = { version = "1.0", features = ["derive"] }
chrono = { version = "0.4", features = ["serde"] }
serde_json = { version = "1.0", features = ["arbitrary_precision"] }
simd-json = "0.14"
tokio-tungstenite = "0.26.2"
brotli = "8.0.2"
ruint = "1.17.2"

[dev-dependencies]
rand = "0.9.2"
tracing-subscriber = { version = "0.3", features = ["env-filter", "fmt"] }
criterion = "0.7"
dotenv = "0.15"
tokio = { version = "1.42", default-features = false, features = [
  "rt-multi-thread",
] }
alloy = { version = "1.0.25", features = ["rpc-client", "reqwest-rustls-tls"] }
alloy-provider = { version = "1.0.25", default-features = false, features = ["throttle", "reqwest", "reqwest-rustls-tls"] }
serde_json = { version = "1.0", features = ["arbitrary_precision"] }


[build-dependencies]
serde_json = "1.0"
rayon = "1"


[profile.release]
opt-level = 3
lto = true
codegen-units = 1
panic = "abort"

 # 开发模式：追求编译速度
[profile.dev]
opt-level = 0
lto = false
codegen-units = 256
debug = 1
incremental = true


[[bench]]
name = "uniswap_v2"
harness = false

[[bench]]
name = "uniswap_v3"
harness = false

[[bench]]
name = "erc_4626"
harness = false
